logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}-${spring.cloud.client.ipAddress}-${INSTANCE_ID:${random.value}-${server.port}}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

who: justokla
