93hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

server:
  port: 2239
  max-http-header-size: 8192
  tomcat.max-threads: 800

#     jdbc:mysql://drds096843499h63.drds.aliyuncs.com:3306/mealtime?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#     mealtime_ro
#     Mealtime20161208


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    name: test
    url: jdbc:mysql://drds5c08708617e9public.drds.aliyuncs.com:3306/pre_2_6?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: pre_2_6
    password: Mealtime_2016
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
      database: 0
      host: 192.168.186.128
      port: 6379
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  jackson:
    mapper:
      allow-final-fields-as-mutators: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration.map-underscore-to-camel-case: true

mapper:
  not-empty: false
  identity: MYSQL
  before: true
  
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  


logging:
  path: /opt/soft/spring-cloud/logs
  file: report.log
  level:
    root: debug
